version = 1

[merge]
method = "squash"
notify_on_conflict = "author"
automerge_label = "automerge"
require_automerge_label = true
delete_branch_on_merge = true

authorized_users = ["sprocket-github-bot[bot]"]

[merge.message]
title = "pull_request_title"
body = "pull_request_body"

[update]
always = true
