packages:
  - 'website'
  - 'packages/*'
  - 'packages/@sprocketui-types/*'
  - 'packages/@sprocketui-vue/packages/*'
  - 'packages/@sprocketui-react/*'
  - '../../nectoutil/NodeKit/packages/*'
  - '../../nectoutil/NodeKit/packages/@necto-react/*'