name: Run tests and upload coverage

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    name: Run tests, coverage, and upload to Codecov
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'renovate[bot]' && github.actor != 'sprocket-github-bot[bot]' && github.actor != 'kodiakhq[bot]' && !startsWith(github.head_ref, 'kodiak/') && !startsWith(github.ref_name, 'kodiak/') }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 2

      - name: Setup pnpm
        uses: pnpm/action-setup@v6

      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run tests with coverage
        run: pnpm run test:coverage

      - name: Upload coverage reports to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: "**/coverage/lcov.info"
          fail_ci_if_error: true
